name: Docker Image CI backend

on:
  push:
    branches: [ "main" ]
    paths:
      - backend
  pull_request:
    branches: [ "main" ]
    paths:
      - backend
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the image
      working-directory: ./backend
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/human-activity-detection-backend
      
    - name: Docker Push Backend
      run: docker push ${{secrets.DOCKER_USER}}/human-activity-detection-backend
